[package]
name = "mini_git"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1 = "0.10.6"
hex = "0.4.3"
clap = { version = "4.4.11", features = ["derive"] }
